
name: Build and Deploy
on:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build Gatsby site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.3.1
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      #- name: Install Project Dependencies
        #run: npm ci
      - name: Install Gatsby CLI
        #run: npm install -g gatsby-cli@2.12.34
        run: npm install --location=global gatsby-cli
      - name : Install Dependencies
        run: npm install
      - name: Build
        run: gatsby build 
      - name: Verify build
        run: ls -la public
      #- name: npm audit build
      #  run: npm audit
      - name: Upload public folder as Package
        uses: actions/upload-artifact@v3
        with:
          name: public-package
          path: public 
  deploy:
    name: Deploy Gatsby site
    runs-on: ubuntu-latest
    needs: npm-audit
    steps:
      - name: Download the public folder to deploy Job
        uses: actions/download-artifact@v3
        with:
          name: public-package
          path: public
      - name: Copy the Public Folder to Ubuntu
        uses: marcodallasanta/ssh-scp-deploy@v1.2.0
        with:
          local: 'public/*'
          remote: '~/public/'
          host: ${{secrets.REMOTE_HOST}}
          user: ${{secrets.REMOTE_USER}}
          key: ${{secrets.SERVER_SSH_KEY}}
          ssh_options: -o StrictHostKeyChecking=no
          pre_upload: sudo rm -rf /var/www/html/*
          #post_upload: ls -la ~/public
          post_upload: sudo mv ~/public/* /var/www/html/
  npm-audit:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout the codebase
        uses: actions/checkout@v3
      - name: Security Component 
        run: |
          npm --version
          npm audit --json